### ISSUE TITLE
ImportError: cannot import name 'discretisers' from 'feature_engine'

### ISSUE THREAD

**Issue by vuphan314** [meelgroup/justicia#1]
@bishwamittra 
Hi Bishwamittra,
Do you know the installation requirements for Ubuntu 21.04?

I got this error:
```
$ python3 benchmarking/script.py 
Traceback (most recent call last):
  File "/home/vhp1/code/justicia/benchmarking/script.py", line 7, in <module>
    from justicia import decision_tree_wrap
  File "/home/vhp1/.local/lib/python3.9/site-packages/justicia/decision_tree_wrap.py", line 16, in <module>
    import justicia.utils as utils
  File "/home/vhp1/.local/lib/python3.9/site-packages/justicia/utils.py", line 8, in <module>
    from feature_engine import discretisers as dsc
ImportError: cannot import name 'discretisers' from 'feature_engine' (/home/vhp1/.local/lib/python3.9/site-packages/feature_engine/__init__.py)
```

Commit:
https://github.com/meelgroup/justicia/tree/8a19b8c5e5fc4948859476a6e0d26190d7507d0e

Thank you.

**Comment by bishwamittra** [comment]
Hi, could you try installing  `pip install feature-engine`. Seems like this is an error of feature-engine package.

**Comment by vuphan314** [comment]
Thanks. I had `feature-engine-1.1.1`, which was too new.

Installing an older version resolves the error.
```bash
python3.7 -m pip install feature-engine==0.4.31
```

I am closing this issue.
